### ISSUE TITLE
app_types is null

### ISSUE THREAD

**Issue by ruifeng96150** [Featuretools/Automated-Manual-Comparison#4]
at Automated Loan Repayment page of following codes:
```
app_types = {}

# Handle the Boolean variables:
for col in app:
    if (app[col].nunique() == 2) and (app[col].dtype == float):
        app_types[col] = vtypes.Boolean

# Remove the `TARGET`
del app_types['TARGET']

print('There are {} Boolean variables in the application data.'.format(len(app_types)))
```
the result should be 0 but not 32

**Comment by WillKoehrsen** [comment]
Sorry, but what exactly is the issue? There are 32 values that are Booleans in the original data that are represented as floats. We need to tell Featuretools to treat these as Booleans and not as Numeric so we create a dictionary mapping the feature to the correct variable type. 
  
This is shown in the Notebook.

![image](https://user-images.githubusercontent.com/17484616/45599558-9daa3280-b9bb-11e8-8919-f14a024a1732.png)
